### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by jopemora** [kerim371/G_Seis#1]
Hi Karim, excellent tool, my friend do you have a user manual?, I am trying to plot the volume I but don't get the configuration plot. thanks!

**Comment by kerim371** [comment]
@jopemora hi

I'm really sorry for the late answer. I hope you forgive me for that

Actually there is no user manual but some necessary information about each module you get in a small window that appears when you click on the module.

There is no possibility to visualize volume data but you can plot it as 2D density plot. This package is designated to use with small 2D data. Of course you can read the whole seismic data to Matlab and then use Matlab all visualization techniques to visualize the volume
